final Map<String, String> en = {
  'choos_your_language': 'Choose Your Language',
  'select_lan_sub': 'Select the language you’re most comfortable with.',
  'continue': 'Continue',
  'whyspers_is_a_private_platform_intended_for_adults_18+':
      'Whyspers is a private platform intended for adults 18+.',
  'please_confirm_your_age_to_continue': 'Please confirm your age to continue.',
  'date_of_birth': 'Date of birth',
  'i_confirm_that_i_am_at_least_18_years_old':
      'I confirm that I am at least 18 years old.',
  'if_you_are_under_18_please_exit_the_app':
      'If you are under 18, please exit the app.',
  'more_than_messages': 'More Than Messages',
  'with_whyspers_connection_becomes_currency':
      'With Whyspers, connection becomes currency.',
  'your_energy_is_the_experience': 'Your Energy Is the Experience',
  "you_don't_need_show_more._you_need_to_be_more":
      "You don't need to show more. You need to be more.",
  'next': 'Next',
  'connection_redefined': 'Connection, Redefined',
  "this_isn't_small_talk_this_is_soul_talk_wrapped_in_intimacy":
      "This isn’t small talk. This is soul talk wrapped in intimacy.",
  'every_whysper_starts_with_a_sign_in': "Every whysper starts with a sign-in.",
  'sign_in_to_connect': 'Sign in to connect',
  'phone_number': 'Phone Number',
  'password': 'Password',
  'remember_me': 'Remember me',
  'forgot_password': 'Forgot Password',
  'sign_in': 'Sign In',
  'or_continue_with': 'Or Continue with',
  "don't_have_an_account": "Don’t have an account?",
  'sing_up': 'Sign Up',
  'male': 'Male',
  'female': 'Female',
  "jane_doe": "Jane Doe",
  "create_your_account_start_a_conversation_they'll_never_forget":
      "Create your account. Start a conversation they'll never forget.",
  'create_your_account_to_unlock_private_access':
      'Create your account to unlock private access',
  'full_name': 'Full Name',
  'name': 'Name',
  'ekramul_haque_anto': 'Ekramul Haque Anto',
  'ekramul_haque': 'Ekramul Haque',
  'confirm_password': 'Confirm Password',
  'sign_up_for_every_whysper': 'Sign Up For Every Whysper',
  'join_whyspers_and_start_connecting': 'oin Whyspers and start connecting',
  'gender': 'Gender',
  'location': 'Location',
  'street_address': 'Street Address',
  'enter_street_address': 'Enter Street Address',
  'enter_zip_code': 'Enter ZIP Code',
  'zip_postal_code': 'ZIP / Postal Code',
  'city': 'City',
  'country': 'Country',

  'dhaka': 'Dhaka',
  'faridpur': 'Faridpur',
  'khulna': 'Khulna',
  'india': 'India',
  'nepal': 'Nepal',
  'bhutan': 'Bhutan',
  'select_country': 'Select Country',
  'select_city': 'Select City',

  "+_new_post": "+ New Post",
  'i_agree_to_the_whyspers_terms_of_service_and_privacy_policy':
      'I agree to the Whyspers Terms of Service\nand Privacy Policy',
  'already_have_an_account': 'Already have an account?',
  'forgot_your_password': 'Forgot Your Password?',
  "it_happens!_enter_your_number_and_we'll_send_a_reset_code_right_away":
      "It happens! Enter your number and we’ll send a reset\ncode right away.",
  'your_mobile_number': 'Your Mobile Number',
  'send_otp_code': 'Send OTP Code',
  'enter_otp_code': 'Enter OTP Code',
  "we've_sent_a_4_digit_code_to_your_phone_please_enter_it_below":
      "We’ve sent a 4-digit code to your phone. Please enter it below.",
  "code_has_sent_to_++8801631926184": "Code has been sent to +8801631926184",
  'you_can_resend_the_code_in_56_seconds':
      'You can resend the code in 56 Seconds',
  'resend_code': 'Resend Code',
  'vefiry': 'Verify',
  'create_new_password': 'Create  New Password',
  "you'are_almost_done!_set_a_new_password_to_finish_resetting":
      "You're almost done! Set a new password to finish resetting.",
  'new_password': 'New Password',
  'confirm_new_password': 'Confirm New Password',
  'please_confirm_your_password': 'Please confirm your password',
  'password_do_not_match': 'Passwords do not match',
  'reset_password': 'Reset Password',
  'password_reset_sucessful': 'Password Reset Successful!',
  'your_password_has_been_updated_you_can_now_log_in_with_your_new_password':
      "Your password has been updated.\nYou can now log in with your new\npassword.",
  'sign_in_now': 'Sign In Now',
  'setting_page': 'Settings Page',
  'personal_information': 'Personal information',
  'secqurity': 'Security',
  'language': 'Language',
  'begin_earning_with_whyspers': 'Begin Earning with Whyspers',
  'monitization': 'Monetization',
  'log_out': 'Log out',
  'skip': 'Skip',
  'pasword_reset_successfull': 'Password Reset\nSuccessful!',
  'are you sure you want to log out from app.\nthis action cannot be undone':
      'Are you sure you want log out from app.\nThis action cannot be undone.',
  'search': 'Search ...',
  'comedy': 'Comedy',
  'content': 'Content',
  'writing': 'Writing',
  'all_whyspers': 'All Whyspers',
  'live_whyspers': 'Live Whyspers',
  'jane_cooper': 'Jane Cooper',
  'how_are_you ?': 'Cómo estás ?',
  'courtney_henry': 'Courtney Henry',
  'marvin_mcKinney': 'Marvin McKinney',
  'cody_fisher': 'Cody Fisher',
  'ralph_edwards': 'Ralph Edwards',
  'wade_warren': 'Wade Warren',
  'darlene_Robertson': 'Darlene Robertson',
  'hi_steven': 'Hi, Steven',
  'hi': 'Hola',
  'steven': 'Steven',
  'search_creators': 'search_creators...',
  'add_story': 'Add Story',
  'anas_islam': 'Anas Islam',
  'package_type': 'Package Type',
  'anas_khan': 'Ans Khan',
  'intimate_visuals_form_my_world_get_closer_than_ever_before':
      'Intimate Visuals from My World Get Closer Than Ever\nBefore | ....',
  'photography': ' Photography',
  '10_minutes_ago': '10 minutes ago',
  'trip': 'Tip',
  "i_wanted_to_my_reflection_what_do_you_really_want_and_in_the_silence_i_heard_it_not_frame_not_followers_just_to_be_seen_truly_seen_thats_night_i_didn't_post_the_world_i_created_something_for_you_someone_who_listens_to_more_than_just_the_sound._who_feels_the_space_between_my_words_welcome_to_my_real_story_no_filters_no_noise_just_whispers":
      'I whispered to my reflection: “What do you really want?” And in the silence, I heard it Not fame. Not followers. Just to be seen. Truly seen. That night, I didn’t post for the world. I created something for you Someone who listens to more than just the sound, Who feels the space between my words. Welcome to my real story. No filters. No noise. Just whispers.',
  'news_feed': 'News Feed',
  'whyspers': 'Whyspers',
  'vault': 'Vault',
  'profile': 'Profile',
  'intimate_visuals_from_my_world_get_closer_than_ever_before':
      'Intimate Visuals from My World Get Closer Than\nEver Before | ....',
  '...more': '...more',
  'following': 'Following',
  'followers': 'Followers',
  'follow': 'follow',
  'comments': 'Comments',
  'english': 'English',
  'add_a_comments': 'Add a comment ...',
  "i_whispered_to_my_reflection_what_do_you_really_want_and_in_the_silence_i_heard_it_not_fame_not_followers_just_to_be_seen":
      "I whispered to my reflection: \"What do you really want?\" And in the silence, I heard it. Not fame. Not followers. Just to be seen.",
  'reply': 'Reply',
  'total_whysper_coins': 'Total Whysper Coins',
  'add_whysper_coins': 'Add Whysper Coins',
  'quick_stats': 'estadísticas rápidas',
  '200_coins': '200 Coins',
  '150_coins': '150 Coins',
  'chat': 'Chat',
  'gifts': 'Gifts',
  'transaction_history': 'Transaction History',
  'purchased_coins': 'Purchased Coins',
  'chat_with_@Alisa': 'Chat with @Alisa',
  'gift_sent_to_@DarkMoon': 'Gift sent to @DarkMoon',
  'select_payment_method': 'Select Payment Method',
  'apple_pay': 'Apple Pay',
  'credit_/debit_card': 'Credit/Debit Card',
  'google_pay': 'Google Pay',
  'continue_payment': 'Continue Payment',
  'settings_page': 'Settings Page',
  'security': 'Security',
  'deactive_status': 'Didactive Status',
  'change_password': 'Change Password',
  "what's_on_your_mind ?":"What’s your mind ?",
  'old_password': 'Old Password',
  'save_Changes': 'Save Changes',
  'password_updated_successfully': 'Password updated successfully',
  "are_you_sure_you_want_to_log_out_from_the_app_this_action_cannot_be_undone":
      "Are you sure you want to log out from the app? This action cannot be undone.",
  'cancel': 'Cancel',
  'notification': 'Notification',
  'system_notifications': 'SYSTEM NOTIFICATIONS',
  'coins_balance_updated': 'Coins Balance Updated',
  'your_wisper_coins_balance_was_updated':
      'Your Whisper Coins balance was\nupdated.',
  'achievement_unlocked!': 'Achievement Unlocked!',
  "you've_earned_a_reward!": "You've earned a reward!",
  'profile_activity': 'Profile Activity',
  'your_profile_was_viewed_23_times_this_week':
      'Your profile was viewed 23 times this\nweek.',
  '2d_ago': '2d ago',
  '3h_ago': '3h ago',
  '2h_ago': '2h ago',
  '6d_ago': '| 6d ago',

  '1d_ago': '1d ago',
  'updates': 'Updates',
  'nora_just_uploaded_a_new_video': 'Nora just uploaded a new video!',
  'nora_just_uploades_a_new_photo!': 'Nora just uploaded a new photo!',
  'sophia_mitchell': 'Sophia Mitchell',
  'user': 'User',
  "digital_creator_music_producer_sharing_my_journey_through_art_and_sound_based_in_los_angeles_new_content_every_tuesday_and_friday":
      "Digital creator | Music producer | Sharing my journey through art and sound. Based in Los Angeles. New content every Tuesday and Friday.",

  'videos': 'Videos',

  'message': 'Message',
  'gallery': 'Gallery',
  'edit_profile': 'Edit Profile',
  'view_profile': 'View Profile',
  'iva_ryan': 'Iva Ryan',
  'frances_swann': 'Frances Swann',
  'art': 'Art',
  'james_hall': 'James Hall',
  'musician': 'Musician',
  'stephanie_nicol': 'stephanie_nicol',

  'dennis_callis': 'Dennis_callis',
  'design': 'Desing',
  'upload_photo': 'Upload Photo',
  'flirt_line': 'Flirt Line',
  "tali_to_me_if_you're_lonely": 'Talk to me if you’re lonely',
  'bio': 'Bio',
  "hey_there_im_a_passionate_content_creator_who_loves_connecting_with_my_fans_one_on_one":
      "Hey there! I'm a passionate content creator who loves connecting with my fans one-on-one.",
  'locaton': 'Locaton',
  'jenny_wilson': 'Jenny Wilson',
  "share_your_world._connect_with_peope_who_want_to_listen_not_just_follow":
      'Share your world. Connect with people who want to\nlisten, not just follow.',

  "whysper_and_earn": "Whysper & Earn",
  "be_more_than_just_followed,_be_felt_apply_to_start_connecting_and_earning_on_whysper":
      "Be more than just followed, be felt. Apply to start connecting and earning on Whysper",
  "identify_information": "Identify Information",
  "upload_valid_id_info":
      "Upload a valid ID (NID / Passport / Driving License)",
  'upload_video': 'Upload Video',
  "hey_there!i'm_a_passionate_content_creator_who_loves_connecting_with_my_fans_one-on-one":
      "Hey there! I'm a passionate content creator who loves connecting with my fans one-on-one.",
  "talk_to_me_if_you're_lonely": "Talk to me if you’re lonely",
  "i_agree_to_the_whyspers_terms_of_service_and_privacy_and_policy":
      "I agree to the Whyspers Terms of Service and Privacy Policy",
  "your_request_has_been_received": "Your Request Has Been\nReceived!",
  "thank_you_for_your_application_our_team_is_reviewing_your_details_carefully_you'll_receive_a_confirmation_by_text_message_once_your_account_is_approved_sit_tight_your_whisper_is_being_heard":
      "Thank you for your application. Our\nteam is reviewing your details\ncarefully. You'll receive a confirmation\nby text message once your account is\napproved. Sit tight, your whisper is\nbeing heard.",
  "set_payout_account": "Set Payout Account",
  "bank_name": "Bank Name",
  "bank_type": "Bank Type",
  "account_holder_name": "Account Holder Name",
  "account_number": "Account Number",
  "islamic_bank_bangladesh_ltd_*9301": "Islamic Bank Bangladesh Ltd *9301",
  "confirm": "Confirm",
  "your_content": "Your Content",
  "4.2k_views": "4.2K views",
  "create_post": "Create Post",
  "public": "Public",
  "private": "Private",
  "friends": "Friends",
  "share_your_thoughts": "share your thoughts...",
  "usd_value": "USD Value",
  "request_payout": "Request Payout",
  "category": "category",
  "unlock": "Unlock",
  "tips": "Tips",
  "quick_trend_line_graph": "Quick trend line graph",
  "yearly": "Yearly",
  "monthly": "Monthly",
  "weekly": "Weekly",
  "daily": "Daily",
  "top_services_by_revenue": "Top Services by Revenue",
  "today": "Today",
  "kathryn_murphy": "Kathryn Murphy",
  "320 coins": "320 coins",
  "120 coins": "120_coins",
  "level_silver": "Level Silver",
  "staten_island_new_york_united_states":
      "Staten Island , New York , United States.",
  "top_fans": "Top Fans",
  "earnings_and_tokens": "Earnings & Tokens",
  "you_received_500_tokens_form_@alex": "You received 500 Tokens from @Alex",
  "your_pay_out_has_been_processed": "Your pay out has been processed",
  "creator_activity": "CREATOR ACTIVITY",
  "you_received_a_new_form_@user59": "You received a new message from @User59",
  "hey_i_wanted_to_ask_about": "Hey, I wanted to ask about...",
  "new_chat_request_form_@fangirl": "New chat request from @FanGirl",
  "active": "Active",
  "upload_intro_video": "Upload Intro Video (Maximum 30 seconds)",
  "profile_photo": "Profile Photo",
  "create_account": "Create Account",
  "only_me": "Only Me",
  "basic_information": "Basic Information",
  "apply_for_monetization": "Apply For\nMonetization",
  "gift_coin": "Gift Coin",
  "type_coin": "Type Coin",
  "showcase_your_item's_worth_to_potential_buyers!_after_listing_your_item_will_be_featured_in_our_marketplace_along_with_your_price_condition_and_important_details_you_have_full_control_to_edit_or_delete_your_listing_whenever_you_want_take_the_step_now_and_convert_your_asset_into_cash":
      "Showcase your item’s worth to potential buyers! After\nlisting, your item will be featured in our marketplace along\nwith your price, condition, and important details. You have\nfull control to edit or delete your listing whenever you\nwant. Take the step now and convert your asset into cash.",
  "send": "Send",
  "you_received_500_tokens_form\n@alex": "You received 500 Tokens from\n@Alex",
  "you_received_a_new_message_form_@user59":
      "You received a new message\nfrom @User59",
  "new_chat_request_from_@FanGirl": "New chat request from @FanGirl",
  "earnings_&_tokens": "Earnings & Tokens",
  "legal":"Legal",
  "support":"Support",
  "delete_account":"Delete Account",
  "this_action_is_permanent_and_cannot_be_undone.All_your_data_will_be_permanently_deleted":"This action is permanent and cannot be\nundone.All your data will be permanently\ndeleted",
  "account_settings":"Account Settings",
  "privacy_data": "Privacy & Data",
  "data_usage_overview":"Data Usage Overview",
  "request_data_deletion":"Request Data Deletion",
  "block_user":"Block User",
  "two_factor":"Two Factor",
  "disable_two-factor_authentication":"Disable Two-Factor Authentication?",
  "turning_off_two-factor_authentication_will_make_your_account_less_secure": "Turning off two-factor authentication will\nmake your account less secure.",
  "verify_your_identity":"Verify Your Identity",
  "please_confirm_your_identity_to_disable_two-factor_authentication":"Please confirm your identity to disable two-factor\nauthentication.",
  "enter_your_account_password":"Enter your account password",
  "blocked_users":"Blocked Users",
  
  


};
