final Map<String, String> es = {
  'choos_your_language': 'Elige tu idioma',
  'select_lan_sub': 'Selecciona el idioma con el que te sientas más cómodo.',
  'continue': 'Continuar',
  'whyspers_is_a_private_platform_intended_for_adults_18+':
      'Whyspers es una plataforma privada destinada a adultos mayores de 18 años.',
  'please_confirm_your_age_to_continue':
      'Por favor, confirma tu edad para continuar.',
  'date_of_birth': 'Fecha de nacimiento',
  'i_confirm_that_i_am_at_least_18_years_old':
      'Confirmo que tengo al menos 18 años.',
  'if_you_are_under_18_please_exit_the_app':
      'Si tienes menos de 18 años, por favor cierra la aplicación.',
  'more_than_messages': 'Más que mensajes',
  'with_whyspers_connection_becomes_currency':
      'Con Whyspers, la conexión se convierte en moneda.',
  'your_energy_is_the_experience': 'Tu energía es la experiencia',
  "you_don't_need_show_more._you_need_to_be_more":
      'No necesitas mostrar más. Necesitas ser más.',
  'next': 'Siguiente',
  'connection_redefined': 'Conexión, redefinida',
  "this_isn't_small_talk_this_is_soul_talk_wrapped_in_intimacy":
      'Esto no es charla trivial. Es conversación del alma envuelta en intimidad.',
  'every_whysper_starts_with_a_sign_in':
      'Cada whysper comienza con un inicio de sesión.',
  'sign_in_to_connect': 'Inicia sesión para conectar',
  'phone_number': 'Número de teléfono',
  'password': 'Contraseña',
  'remember_me': 'Recuérdame',
  'forgot_password': '¿Olvidaste tu contraseña?',
  'sign_in': 'Iniciar sesión',
  'or_continue_with': 'O continúa con',
  "don't_have_an_account": '¿No tienes una cuenta?',
  'sing_up': 'Regístrate',
  "what's_on_your_mind ?":"¿Qué hay en tu mente?",

  "create_your_account_start_a_conversation_they'll_never_forget":
      'Crea tu cuenta. Inicia una conversación que nunca olvidarán.',
  'create_your_account_to_unlock_private_access':
      'Crea tu cuenta para desbloquear el acceso privado',
  'full_name': 'Nombre completo',
  'ekramul_haque_anto':
      'Ekramul Haque Anto', // (usually names are not translated)
  'confirm_password': 'Confirmar contraseña',
  'sign_up_for_every_whysper': 'Regístrate para cada Whysper',
  'join_whyspers_and_start_connecting': 'Únete a Whyspers y empieza a conectar',
  'gender': 'Género',
  'location': 'Ubicación',
  'street_address': 'Dirección',
  'zip_postal_code': 'Código postal',
  'enter_street_address': 'Ingrese la dirección',
  'enter_zip_code': 'Ingrese el código postal',
  'city': 'Ciudad',
'dhaka': 'Dhaka',
'faridpur': 'Faridpur',
'khulna': 'Khulna',
'country': 'País',
'india': 'India',
'nepal': 'Nepal',
'bhutan': 'Bután',
'select_country': 'Seleccionar país',
'select_city': 'Seleccionar ciudad',

  'i_agree_to_the_whyspers_terms_of_service_and_privacy_policy':
    'Acepto los Términos de servicio de Whyspers\ny la Política de privacidad',

  'already_have_an_account': '¿Ya tienes una cuenta?',
  'forgot_your_password': '¿Olvidaste tu contraseña?',
  "it_happens!_enter_your_number_and_we'll_send_a_reset_code_right_away":
      '¡Pasa a veces! Ingresa tu número y te enviaremos un código de restablecimiento de inmediato.',
  'your_mobile_number': 'Tu número móvil',
  'send_otp_code': 'Enviar código OTP',
  'enter_otp_code': 'Ingresar código OTP',
  "we've_sent_a_4_digit_code_to_your_phone_please_enter_it_below":
      'Hemos enviado un código de 4 dígitos a tu teléfono. Por favor ingrésalo abajo.',
  "code_has_sent_to_++8801631926184":
      'El código ha sido enviado a +8801631926184',
  'you_can_resend_the_code_in_56_seconds':
      'Puedes reenviar el código en 56 segundos',
  'resend_code': 'Reenviar código',
  'vefiry': 'Verificar',
  'create_new_password': 'Crear nueva contraseña',
  "you'are_almost_done!_set_a_new_password_to_finish_resetting":
      '¡Casi has terminado! Establece una nueva contraseña para finalizar el restablecimiento.',
  'new_password': 'Nueva contraseña',
  'confirm_new_password': 'Confirmar nueva contraseña',
  'reset_password': 'Restablecer contraseña',
  'password_reset_sucessful': '¡Contraseña restablecida con éxito!',
  'your_password_has_been_updated_you_can_now_log_in_with_your_new_password':
      'Tu contraseña ha sido actualizada. Ahora puedes iniciar sesión con tu nueva contraseña.',
  'sign_in_now': 'Inicia sesión ahora',
  'setting_page': 'Página de configuración',
  'personal_information': 'Información personal',
  'secqurity': 'Seguridad',
  'language': 'Idioma',
  'begin_earning_with_whyspers': 'Comienza a ganar con Whyspers',
  'monitization': 'Monetización',
  'log_out': 'Cerrar sesión',
  'skip': 'Omitir',
  'male': 'Hombre',
  'female': 'Mujer',

  'search': 'Buscar ...',
'all_whyspers': 'Todos los Whyspers',
'live_whyspers': 'Whyspers en vivo',
'jane_cooper': 'Jane Cooper',
'how_are_you ?': '¿Cómo estás?',
'courtney_henry': 'Courtney Henry',
'marvin_mcKinney': 'Marvin McKinney',
'cody_fisher': 'Cody Fisher',
'ralph_edwards': 'Ralph Edwards',
'wade_warren': 'Wade Warren',
'darlene_Robertson': 'Darlene Robertson',
'hi_shaven': 'Hola, Steven',
'hi': '¡Hola!',
'shaven': 'Steven',
"+_new_post": "+ Nueva publicación",
'search_creators': 'buscar_creadores...',
'add_story': 'Agregar historia',
'anas_islam': 'Anas Islam',
'anas_khan': 'Ans Khan',
'name': 'Nombre',

'intimate_visuals_form_my_world_get_closer_than_ever_before':
    'Visuales íntimos de mi mundo, acércate como nunca antes | ....',
'photography': '| Fotografía',
'10_minutes_ago': 'Hace 10 minutos',
'trip': 'Propina',
"i_wanted_to_my_reflection_what_do_you_really_want_and_in_the_silence_i_heard_it_not_frame_not_followers_just_to_be_seen_truly_seen_thats_night_i_didn't_post_the_world_i_created_something_for_you_someone_who_listens_to_more_than_just_the_sound._who_feels_the_space_between_my_words_welcome_to_my_real_story_no_filters_no_noise_just_whispers":
    'Le susurré a mi reflejo: “¿Qué es lo que realmente quieres?” Y en el silencio lo escuché. No fama. No seguidores. Solo ser visto. Realmente visto. Esa noche no publiqué para el mundo. Creé algo para ti. Alguien que escucha más que solo el sonido, que siente el espacio entre mis palabras. Bienvenido a mi historia real. Sin filtros. Sin ruido. Solo susurros.',
'news_feed': 'Noticias',
'whyspers': 'Whyspers',
'vault': 'Bóveda',
'profile': 'Perfil',
'intimate_visuals_from_my_world_get_closer_than_ever_before':
    'Visuales íntimos de mi mundo, acércate como\nnunca antes | ....',
'...more': '...más',
'following': 'Siguiendo',
'follow': 'Seguir',
'comments': 'Comentarios',
'add_a_comments': 'Agregar un comentario ...',
"i_whispered_to_my_reflection_what_do_you_really_want_and_in_the_silence_i_heard_it_not_fame_not_followers_just_to_be_seen":
    "Le susurré a mi reflejo: \"¿Qué es lo que realmente quieres?\" Y en el silencio lo escuché. No fama. No seguidores. Solo ser visto.",
'reply': 'Responder',
'total_whysper_coins': 'total por qué monedas',
'add_whysper_coins': 'Agregar Whysper Coins',
'quick_stats': 'Estadísticas rápidas',
'200_coins': '200 Monedas',
'150_coins': '150 Monedas',
'chat': 'charlar',
'gifts': 'Regalos',
'transaction_history': 'Historial de transacciones',
'purchased_coins': 'Monedas compradas',
'chat_with_@Alisa': 'Chatear con @Alisa',
'gift_sent_to_@DarkMoon': 'Regalo enviado a @DarkMoon',
'select_payment_method': 'Seleccionar método de pago',
'apple_pay': 'Apple Pay',
'credit_/debit_card': 'Tarjeta de crédito/débito',
'google_pay': 'Google Pay',
'continue_payment': 'Continuar pago',
'settings_page': 'Página de configuración',
'security': 'Seguridad',
'deactive_status': 'Estado desactivado',
'change_password': 'Cambiar contraseña',
'please_confirm_your_password': 'Por favor confirma tu contraseña',
'password_do_not_match': 'Las contraseñas no coinciden',
'password_updated_successfully': 'Contraseña actualizada con éxito',

'old_password': 'Contraseña anterior',
'save_Changes': 'Guardar cambios',
"are_you_sure_you_want_to_log_out_from_the_app_this_action_cannot_be_undone":
    "¿Estás seguro de que quieres cerrar sesión en la aplicación? Esta acción no se puede deshacer.",
'cancel': 'Cancelar',
'notification': 'Notificación',
'system_notifications': 'NOTIFICACIONES DEL SISTEMA',
'coins_balance_updated': 'Saldo de monedas actualizado',
'your_wisper_coins_balance_was_updated': 'Tu saldo de Whisper Coins fue\nactualizado.',
'achievement_unlocked!': '¡Logro desbloqueado!',
"you've_earned_a_reward!": "¡Has ganado una recompensa!",
'profile_activity': 'Actividad del perfil',
'your_profile_was_viewed_23_times_this_week': 'Tu perfil fue visto 23 veces esta\nsemana.',
'2d_ago': 'Hace 2 días',
'6d_ago': '| Hace 6 días',
'3h_ago': 'Hace 3 horas',
'2h_ago': 'Hace 2 horas',
'followers': 'Seguidores',
"profile_photo": "Foto de perfil",




'1d_ago': 'Hace 1 día',
'updates': 'Actualizaciones',
'nora_just_uploaded_a_new_video': '¡Nora acaba de subir un nuevo\nideo!',
'nora_just_uploades_a_new_photo!': '¡Nora acaba de subir una nueva\nfoto!',
'sophia_mitchell': 'Sophia Mitchell',
'user': 'Usuario',
"digital_creator_music_producer_sharing_my_journey_through_art_and_sound_based_in_los_angeles_new_content_every_tuesday_and_friday":
"Creador digital | Productor musical | Compartiendo mi viaje a través del arte y el sonido. Con sede en Los Ángeles. Nuevo contenido cada martes y viernes.",
'videos': 'Videos',
'message': 'Mensaje',
'gallery': 'Galería',
'comedy': 'Comedia',
'content': 'Contenido',
'writing': 'Escritura',
'package_type': 'Tipo de paquete',
'english': 'Inglés',
'are you sure you want to log out from app.\nthis action cannot be undone': 
'¿Estás seguro de que quieres cerrar sesión en la aplicación?\nEsta acción no se puede deshacer.',
'edit_profile': 'Editar perfil',
'view_profile': 'Ver perfil',
'iva_ryan': 'Iva Ryan',
'frances_swann': 'Frances Swann',
'art': 'Arte',
'james_hall': 'James Hall',
'musician': 'Músico',
'stephanie_nicol': 'Stephanie Nicol',
'dennis_callis': 'Dennis Callis',
'design': 'Diseño',
'upload_photo': 'Subir foto',
'flirt_Line': 'Línea coqueta',
"tali_to_me_if_you're_lonely": 'Háblame si te sientes solo',
'bio': 'Biografía',
"hey_there_im_a_passionate_content_creator_who_loves_connecting_with_my_fans_one_on_one":
"¡Hola! Soy un apasionado creador de contenido que ama conectarse con mis fans de manera personal.",
'locaton': 'Ubicación',
"share_your_world._connect_with_peope_who_want_to_listen_not_just_follow": 
"Comparte tu mundo. Conéctate con personas que quieran escucharte,\nno solo seguirte.",



"whysper_and_earn": "Whysper y Gana",
"be_more_than_just_followed,_be_felt_apply_to_start_connecting_and_earning_on_whysper": "Sé más que seguido, sé sentido. Aplica para empezar a conectar y ganar en Whysper",
"identify_information": "Identificar información",
"upload_valid_id_info": "Sube una identificación válida (DNI / Pasaporte / Licencia de Conducir)",
"upload_video": "Subir video",
"hey_there!i'm_a_passionate_content_creator_who_loves_connecting_with_my_fans_one-on-one": "¡Hola! Soy un apasionado creador de contenido que ama conectar con mis fans de manera personal.",
"flirt_line": "Línea coqueta",
"talk_to_me_if_you're_lonely": "Háblame si estás sol@",
"i_agree_to_the_whyspers_terms_of_service_and_privacy_and_policy": "Acepto los Términos de Servicio y la Política de Privacidad de Whyspers",
"your_request_has_been_received": "¡Tu solicitud ha sido recibida!",
"thank_you_for_your_application_our_team_is_reviewing_your_details_carefully_you'll_receive_a_confirmation_by_text_message_once_your_account_is_approved_sit_tight_your_whisper_is_being_heard": "Gracias por tu solicitud. Nuestro equipo está revisando tus datos cuidadosamente. Recibirás una confirmación por mensaje de texto una vez que tu cuenta sea aprobada. Ten paciencia, tu susurro está siendo escuchado.",
"set_payout_account": "Configurar cuenta de pago",
"bank_name": "Nombre del banco",
"bank_type": "Tipo de banco",
"account_holder_name": "Nombre del titular de la cuenta",
"account_number": "Número de cuenta",
"islamic_bank_bangladesh_ltd_*9301": "Banco Islámico de Bangladesh Ltd *9301",
"confirm": "Confirmar",
"your_content": "Tu contenido",
"4.2k_views": "4.2K vistas",
"create_post": "Crear publicación",
"public": "Público",
"private": "Privado",
"friends": "Amigos",
"share_your_thoughts": "comparte tus pensamientos...",
"usd_value": "Valor en USD",
"request_payout": "Solicitar pago",
"category": "Categoría",
"unlock": "Desbloquear",
"tips": "Consejos",
"quick_trend_line_graph": "Gráfico de tendencia rápida",
"yearly": "Anual",
"monthly": "Mensual",
"weekly": "Semanal",
"daily": "Diario",
"top_services_by_revenue": "Servicios principales por ingresos",
"today": "Hoy",
"kathryn_murphy": "Kathryn Murphy",
"320 coins": "320 monedas",
"120 coins": "120 monedas",
"level_silver": "Nivel Plata",
"staten_island_new_york_united_states": "Staten Island, Nueva York, Estados Unidos.",
"top_fans": "Mejores fans",
"earnings_and_tokens": "Ganancias y Tokens",
"you_received_500_tokens_form_@alex": "Recibiste 500 Tokens de @Alex",
"your_pay_out_has_been_processed": "Tu pago ha sido procesado",
"creator_activity": "ACTIVIDAD DEL CREADOR",
"you_received_a_new_form_@user59": "Recibiste un nuevo mensaje de @User59",
"hey_i_wanted_to_ask_about": "Hola, quería preguntar sobre...",
"new_chat_request_form_@fangirl": "Nueva solicitud de chat de @FanGirl",
"active": "Activo",
"upload_intro_video": "Sube un video de introducción (máximo 30 segundos)",
"create_account": "Crear cuenta",
"only_me": "Solo yo",
"basic_information": "Información básica",
"apply_for_monetization": "Solicitar monetización",
 'hi_steven':'Hi, Steven',
 "jane_doe": "Jane Doe",
 "gift_coin": "Moneda de regalo",
 "type_coin": "Tipo Moneda",
 
"showcase_your_item's_worth_to_potential_buyers!_after_listing_your_item_will_be_featured_in_our_marketplace_along_with_your_price_condition_and_important_details_you_have_full_control_to_edit_or_delete_your_listing_whenever_you_want_take_the_step_now_and_convert_your_asset_into_cash": "¡Muestra el valor de tu artículo a posibles compradores! Después\nde listar, tu artículo se mostrará en nuestro mercado junto\ncon tu precio, estado y detalles importantes. Tienes\ncontrol total para editar o eliminar tu publicación cuando\nquieras. Da el paso ahora y convierte tu activo en efectivo.",
"send": "Enviar",
"you_received_500_tokens_form\n@alex": "Recibiste 500 tokens de\n@Alex",
"you_received_a_new_message_form_@user59":"Recibiste un nuevo mensaje\nde @User59",
"new_chat_request_from_@FanGirl": "Nueva solicitud de chat de @FanGirl",
"earnings_&_tokens": "Ganancias y tokens",
"legal":"Legal",
"support":"Apoyo",
"delete_account":"Eliminar cuenta",
"this_action_is_permanent_and_cannot_be_undone.All_your_data_will_be_permanently_deleted":"Esta acción es permanente y no se puede\ndeshacer. Todos sus datos se eliminarán\npermanentemente.",
"account_settings": "Configuración de la cuenta",
"privacy_data": "Privacidad y Datos",
"data_usage_overview": "Resumen del uso de datos",
"request_data_deletion": "Solicitar eliminación de datos",
"block_user": "Bloquear usuario",
"two_factor": "Dos factores",
"disable_two-factor_authentication":"¿Desactivar la autenticación de dos factores?",
"verify_your_identity": "Verifica tu identidad",
"enter_your_account_password": "Introduce la contraseña de tu cuenta",
"blocked_users": "Usuarios bloqueados"













 




};
